---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-butler-ingest
  labels:
    app: ingest
    site: sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
      site: sts
  template:
    metadata:
      labels:
        app: ingest
        site: sts
    spec:
      initContainers:
      - name: "fix-secret-permissions"
        image: "ghcr.io/lsst-dm/embargo-butler-ingest:prod"
        command:
        - "/bin/bash"
        - "-c"
        - |
          cp -RL /secrets-raw/* /secrets
          chmod 0400 /secrets/*
        volumeMounts:
        - mountPath: /secrets-raw
          name: db-auth
          readOnly: true
        - mountPath: /secrets
          name: secrets
      containers:
      - name: ingest
        image: "ghcr.io/lsst-dm/embargo-butler-ingest:prod"
        env:
        - name: S3_ENDPOINT_URL
          value: https://s3dfrgw.slac.stanford.edu
        - name: REDIS_HOST
          value: redis
        - name: BUCKET
          value: rubin-sts
        - name: BUTLER_REPO
          value: /repo/ir2
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3
              key: s3_access
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: s3_key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /home/lsst/.lsst
          name: secrets
      volumes:
      - name: secrets
        emptyDir: {}
      - name: db-auth
        secret:
          secretName: db-auth
